---
on:
  workflow_dispatch:
    inputs:
      package_module:
        description: Release python package
        required: true
        default: false
        type: boolean

jobs:
  promote_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install poetry
        run: pip3 install poetry
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'poetry'
      - name: Setup python environment
        run: |
          poetry install
      - name: Promote package to Release
        run: |
          export RELEASE_TAG=$(poetry run semantic-release print-version --current)
          echo "Promoting Release tag: $RELEASE_TAG"
          gh release create $RELEASE_TAG --title $RELEASE_TAG --notes "Release $RELEASE_TAG"        

